[workspace]
name = "calibration-cost-sensitive-learning"
version = "0.1.0"
description = "Probabilistic calibration of cost-sensitive learning"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Olivier Grisel <olivier@probabl.ai>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
generate-predictions = { cmd = "python _generate_predictions.py", cwd = "content/python_files" }

[dependencies]
jupyterlab = ">=4.6.1,<5"
numpy = ">=2.0.1,<3"
scipy = ">=1.14.0,<2"
scikit-learn = ">=1.9.0,<2"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.1,<4"
jupytext = ">=1.16.4,<2"
notebook = ">=7.2.1,<8"
fastparquet = ">=2024.11.0,<2025"
imbalanced-learn = ">=0.14.2,<1"
plotly = ">=6.2.0,<7"
skrub = ">=0.6.0,<0.7"
skore = ">=0.11.0,<0.20"

[feature.dev.dependencies]
ipykernel = "*"

[feature.lint.dependencies]
ruff = "*"
black = "*"

[feature.doc.dependencies]
jupyter-book = ">=1.0.0,<2"
jupyterlite = "==0.8.1"
jupyterlite-pyodide-kernel = "==0.8.1"
python-libarchive-c = "*"

[feature.doc.tasks]

create-notebooks-dir = { cmd = "mkdir -p ./content/notebooks" }
copy-pickles = { cmd = "cp ./content/python_files/*.joblib ./content/notebooks/", depends-on = ["create-notebooks-dir"] }
convert-to-notebooks = { cmd = "jupytext --to notebook ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks" }
convert-to-executed-notebooks = { cmd = "jupytext --to notebook --execute ./content/python_files/*.py && mkdir -p ./content/notebooks && mv ./content/python_files/*.ipynb ./content/notebooks", depends-on = ["create-notebooks-dir", "copy-pickles"] }
build-book = { cmd = "jupyter-book build book", depends-on = ["convert-to-notebooks"] }
build-jupyterlite = { cmd = "jupyter lite build --contents content --output-dir dist", cwd = "jupyterlite" }
serve-jupyterlite = { cmd = "python -m http.server", cwd = "jupyterlite/dist", depends-on = ["build-jupyterlite"] }

[environments]
lint = ["lint"]
doc = ["doc"]
dev = ["dev", "doc", "lint"]
